# Color theme
include ../themes/Catppuccin-Mocha.conf

# Fonts
font_size 13
# kitty uses fontconfig for fallback, so the following is not needed. The first entry
font_family CodeNewRoman Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

# Cursor
cursor_shape block
cursor_beam_thickness 8.0
cursor_blink_interval 0.6 ease-in-out

# Window
scrollback_lines 10000
window_padding_width 4 6
background_opacity 0.8
# blur 强度由 niri 控制
background_blur 1 

# bar
hide_window_decorations no
scrollbar never

# url
url_style straight
underline_hyperlinks hover
modify_font underline_thickness 50%
