clear_all_shortcuts yes

# Font size
map ctrl+equal change_font_size all +1.0
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Copy & Paste
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Send a literal newline on Shift+Enter.
map shift+enter send_text all \n
