## Migrated from ~/.config/wezterm/modules/mousebindings.lua

# wezterm copied completed mouse selections to the clipboard.
copy_on_select clipboard

# Right click paste from clipboard.
mouse_map right press ungrabbed,grabbed paste_from_clipboard

# kitty 暂不支持使用滚轮进行字体缩放
mouse_map ctrl+middle press ungrabbed,grabbed change_font_size all 0
