auto_reload_config 0.1



# window
hide_window_decorations titlebar-only
window_padding_width 15
background_opacity 0.8
background_blur 10




# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include themes/Catppuccin-Mocha.conf
# END_KITTY_THEME

# font
font_size 13