# vim: ft=dosini
[Metadata]
Name=Catppuccin Mocha Blue Mellow Blur
Version=1.0
Author=justTOBBI, Isabelinc, Kurome
Description=Catppuccin Mocha Blue colors with Mellow rounded blur layout
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=0

# Unselected candidate color
# Text
NormalColor=#cdd6f4
# Selected candidate color
# Base
HighlightCandidateColor=#1e1e2e
# Input character color

# KWin 下启用模糊
EnableBlur=True
# 模糊遮罩
BlurMask=blur-mask.svg
# 竖排列表时使用所有横向空间高亮
FullWidthHighlight=True

# Blue
HighlightColor=#89b4fa
# Input character background color
# Surface 0
HighlightBackgroundColor=#313244

[InputPanel/BlurMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/TextMargin]
Left=9
Right=9
Top=6
Bottom=7

[InputPanel/Background]
# Surface 0
Color=#313244
Image=panel.svg
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[InputPanel/Background/Margin]
Left=15
Right=15
Top=15
Bottom=15

[InputPanel/Background/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/Highlight]
# Blue
Color=#89b4fa
Image=highlight.svg
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[InputPanel/Highlight/Margin]
Left=15
Right=15
Top=10
Bottom=10

[InputPanel/Highlight/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/Highlight/HighlightClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/ContentMargin]
Left=9
Right=9
Top=7
Bottom=7

[InputPanel/PrevPage]
Image=

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/ShadowMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu]
Font=Sans 10
# Text
NormalColor=#cdd6f4
# Base
HighlightCandidateColor=#1e1e2e
Spacing=0

[Menu/Background]
# Surface 0
Color=#313244
Image=panel.svg
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/Background/Margin]
Left=11
Right=11
Top=11
Bottom=11

[Menu/Background/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/ContentMargin]
Left=11
Right=11
Top=11
Bottom=11

[Menu/Highlight]
# Blue
Color=#89b4fa
Image=highlight.svg
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Highlight/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/Separator]
# Base
Color=#1e1e2e
Image=
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/Separator/Margin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/Separator/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/CheckBox]
Image=radio.png
Color=#cdd6f4
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/CheckBox/Margin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/CheckBox/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/SubMenu]
Image=arrow.png
Color=#cdd6f4
BorderColor=#00000000
BorderWidth=0
Overlay=
Gravity="Top Left"
OverlayOffsetX=0
OverlayOffsetY=0
HideOverlayIfOversize=False

[Menu/SubMenu/Margin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/SubMenu/OverlayClipMargin]
Left=0
Right=0
Top=0
Bottom=0

[Menu/TextMargin]
Left=6
Right=6
Top=6
Bottom=6
